source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'CloudupKit_Example', :exclusive => true do
  pod "CloudupKit", :path => "../"
end

target 'CloudupKit_Tests', :exclusive => true do
  pod "CloudupKit", :path => "../"

  pod 'FBSnapshotTestCase'
end
